### PR TITLE
client: add WebRTC transport

### PR DESCRIPTION
**Pull request by melekes**
Refs https://github.com/paritytech/smoldot/issues/1712

Additional links:
- [specification](https://github.com/libp2p/specs/pull/412)
- [implementation](https://github.com/libp2p/rust-libp2p/pull/2622)

### CODE REVIEW

**Comment by melekes** [comment]
Currently fails with:

```
2022-07-06 12:23:05.090 DEBUG tokio-runtime-worker webrtc_sctp::association::association_internal: [] failed to retransmit init (n_rtos=3): ErrInitNotStoredToSend

2022-07-05 17:00:32.100 DEBUG tokio-runtime-worker webrtc_dtls::conn: server: discarded duplicated packet (epoch: 0, seq: 5)

2022-07-06 17:25:55.063  WARN tokio-runtime-worker webrtc::peer_connection::peer_connection_internal: Failed to start manager dtls: Alert is Fatal or Close Notify
2022-07-06 17:25:55.063  WARN tokio-runtime-worker webrtc::peer_connection::peer_connection_internal: Failed to start SCTP: DTLS not established
2022-07-06 17:25:55.063  WARN tokio-runtime-worker webrtc::peer_connection::peer_connection_internal: undeclared_media_processor failed to open SrtcpSession  
2022-07-06 17:25:55.063  WARN tokio-runtime-worker webrtc::peer_connection::peer_connection_internal: undeclared_media_processor failed to open SrtpSession 
```

Also looks like we're opening 3 connections instead of 1 (idk why):

```
2022-07-05 17:07:18.503 DEBUG tokio-runtime-worker libp2p_swarm: Connection attempt to PeerId("12D3KooWNzV2jgjvgCThUWWaKAoCTmp1DvQKHwa3SjDBBHxr9MV7") failed with Transport([("/ip4/127.0.0.1/udp/4000/x-webrtc/14B0152CE53D6F3229A81D5A0F080CAEC7682C24C0F805373B9674A279AA4FE8/p2p/12D3KooWNzV2jgjvgCThUWWaKAoCTmp1DvQKHwa3SjDBBHxr9MV7", Other(Custom { kind: Other, error: InternalError("data channel opening took longer than 10 seconds (see logs)") }))]).
2022-07-05 17:07:18.503 DEBUG tokio-runtime-worker libp2p_swarm: Connection attempt to PeerId("12D3KooWNzV2jgjvgCThUWWaKAoCTmp1DvQKHwa3SjDBBHxr9MV7") failed with Transport([("/ip4/127.0.0.1/udp/4000/x-webrtc/14B0152CE53D6F3229A81D5A0F080CAEC7682C24C0F805373B9674A279AA4FE8/p2p/12D3KooWNzV2jgjvgCThUWWaKAoCTmp1DvQKHwa3SjDBBHxr9MV7", Other(Custom { kind: Other, error: InternalError("data channel opening took longer than 10 seconds (see logs)") }))]).
```

Probably connected to ^:

```
2022-07-06 12:22:42.675  WARN tokio-runtime-worker webrtc_ice::agent::agent_selector: discard message from (udp4 host 127.0.0.1:4000), unknown TransactionID 0xTransactionId([63, 26, 201, 25, 101, 39, 85, 203, 73, 209, 203, 18])
```

**Comment by melekes** [comment]
TCP transport also opens 2-3 connections, so it must be substrate who wants that number of connections. However TCP transport succeeds, while WebRTC transport fails to establish even 1 connection. I think it’s because **webrtc-rs wasn’t designed for multiple connections between two parties with same certificates**.

Turns out WebRTC transport wasn’t working because of Kademlia, which was trying to establish a second/third connection IN THE SAME TIME when the node was dialing a bootnode. WebRTC transport does not work when you’re trying to create multiple connections between two parties with the same certificates.

2 bugs left:
1) Short buffer to be filled

```
2022-07-08 13:44:36.715 DEBUG tokio-runtime-worker libp2p_swarm: Connection closed with error Handler(B(Upgrade(Apply(Custom { kind: Other, error: "Short buffer to be filled" })))): Connected { endpoint: Dialer { address: "/ip4/127.0.0.1/udp/4000/x-webrtc/5956172B760F3126A6E2D175A5444035A44C1D8160138C10A323CB0857064DEB/p2p/12D3KooWNzV2jgjvgCThUWWaKAoCTmp1DvQKHwa3SjDBBHxr9MV7", role_override: Dialer }, peer_id: PeerId("12D3KooWNzV2jgjvgCThUWWaKAoCTmp1DvQKHwa3SjDBBHxr9MV7") }; Total (peer): 0
```

2) `Bob` fails to reconnect to `Alice` after ^.

```
2022-07-08 13:45:25.056 DEBUG tokio-runtime-worker webrtc_dtls::conn: client: received packet of next epoch, queuing packet
2022-07-08 13:45:25.056 DEBUG tokio-runtime-worker webrtc_dtls::conn: client: received packet of next epoch, queuing packet
2022-07-08 13:45:25.737 TRACE tokio-runtime-worker sub-libp2p: Libp2p => Reach failure for Some(PeerId("12D3KooWNzV2jgjvgCThUWWaKAoCTmp1DvQKHwa3SjDBBHxr9MV7")) through "/ip4/127.0.0.1/udp/4000/x-webrtc/5956172B760F3126A6E2D175A5444035A44C1D8160138C10A323CB0857064DEB/p2p/12D3KooWNzV2jgjvgCThUWWaKAoCTmp1DvQKHwa3SjDBBHxr9MV7": Other(Custom { kind: Other, error: A(InternalError("data channel opening took longer than 10 seconds (see logs)")) })
```

**Comment by mxinden** [comment]
> I think it’s because **webrtc-rs wasn’t designed for multiple connections between two parties with same certificates**.

Do I understand correctly that implementations have no way to differentiate incoming data by connection given that both endpoints use the same certificate **and** the same UDP port @melekes?

**Comment by melekes** [comment]
> > I think it’s because **webrtc-rs wasn’t designed for multiple connections between two parties with same certificates**.
> 
> Do I understand correctly that implementations have no way to differentiate incoming data by connection given that both endpoints use the same certificate **and** the same UDP port @melekes?

the same certificate **and** the same UDP port **and** the same ICE credentials (username/password, both equal to DTLS fingerprint). I haven't tried the scenario with different ICE credentials.

**Comment by mxinden** [comment]
> I haven't tried the scenario with different ICE credentials.

Would be great in case that would allow multiple connections between two peers. From what I can tell based on https://github.com/libp2p/specs/pull/412 we could use a random string for username+password in the initial STUN for each connection, right?

**Comment by melekes** [comment]
If we disable fingerprint verification on the server (https://github.com/libp2p/specs/pull/412#discussion_r912791493), sure.

**Comment by melekes** [comment]
Waiting for https://github.com/paritytech/substrate/pull/12256 and https://github.com/paritytech/substrate/pull/12085/files to be merged, which themselves depend on https://github.com/libp2p/rust-libp2p/pull/2931/files.

**Comment by mxinden** [comment]
> which themselves depend on https://github.com/libp2p/rust-libp2p/pull/2931/files.

Sorry for the delay here. I am on it :)

**Pull request closed without merging**
